Develop
Cra5h23/java-filmorate pull request #30
Opened 2024-04-09 05:28 UTC by Cra5h23

Все задачи выполнены

2024-04-09 13:45 UTC, kvach2avl reviewed
Хорошая собралась команда и отличная получилась работа!
Супер, что выбрали усложнённые варианты исполнения фич (список режиссеров на фильм вместо одного, поиск по нескольким параметрам и т.д.).
Заметно, что никаких особых сложностей архитектурного плана так же не возникало.

Рекомендация самого общего плана: пожалуйста, придерживайтесь единого стиля именования классов и интерфейсов. Сейчас часть фич реализуется с помощью DAO-интерфейсов и их реализаций, а часть с помощью Storage/DbStorage.
Отдельное пожелание в части README.md. Просьба дополнить его кратким описанием:
1. выполненных фич;
2. состава команды.
Остальные замечания и рекомендации приводятся ниже, думаю, что особых сложностей с ними не будет.

2024-04-09 13:45 UTC, kvach2avl commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +                    if (value > 1895) {
Зачем так сложно и запутанно, почему не воспользоваться тем, что жанр передаётся в params[1], а год в params[2] ?
Ведь если когда-нибудь в БД будет более 1895 жанров и/или год рождения кино начнут отсчитывать от рождества Христова, то этот код может доставить много "веселых минут отладки" ...

2024-04-09 13:45 UTC, kvach2avl commented on src/main/java/ru/yandex/practicum/filmorate/service/film/impl/FilmServiceImpl.java
> +        List<Like> likes = likeDao.getAllFilmLikes();
Не самая хорошая идея выгружать всю БД в память приложения.
Если предположить, что приложение работает в реальных условиях и в БД хотя бы миллион фильмов и каждый фильм понравился хотя бы 100 пользователям, то этот список получится довольно большим. Нужно его как-то ограничить, но без ограничений на качество рекомендаций.
В идеале необходимо переписать этот метод таким образом, чтобы большая часть логики принятия решения о списке фильмов реализовывалась на стороне БД. Выбрать топ-N пользователей, которые лайкнули те же фильмы, что и указанный пользователь можно одним запросом (основной критерий: чем больше совпадений по лайкам, тем больше шансов у такого пользователя попасть в топ). Вторым запросом получить все те фильмы которые они лайкнули за вычетом тех, которые уже лайкнул этот пользователь. Вот и список рекомендаций

2024-04-09 13:45 UTC, kvach2avl commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewRatingDaoImpl.java
> +                "where review_id = ? and user_id = ? and islike = ?";
В таблице reviewratings первичным ключом является пара review_id+user_id, достаточно оставить в условии where только их. Вставлять в условие удаления значение islike смысла нет.
По этой же причине в сам метод delete не имеет смысл передавать полноценный ReviewRating, достаточно пары идентификаторов

2024-04-09 13:45 UTC, kvach2avl commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            "   sum(case when rr.islike then 1 else 0 end) - " +
подобные конструкции заставляют задуматься: может лучше хранить в БД не булевый признак (да / нет), а сразу числовое значение (+1 / -1)? Тогда и арифметика упрощается (останется только sum(review_value)) и возможности модернизации появляются (если завтра захочется поддержать более точную оценку и ввести шкалу -5..+5, например, то код можно не менять)

2024-04-09 13:45 UTC, kvach2avl commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            "coalesce(" +
Лучше делать не coalesce() от sum(), а наоборот - sum() от coalesce(). Хотя бы один null в операторе суммирования может превратить результат в null, поэтому лучше заменить его нулём и продолжить суммирование, а не обнулять всю сумму

2024-04-11 04:17 UTC, raaCodeCat commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewRatingDaoImpl.java
> +                "where review_id = ? and user_id = ? and islike = ?";
Согласен, параметр лишний. Был добавлен, чтобы не удалить лайк при попытке удалил дизлайк, но такая проверка выполняется на уровне сервиса.

2024-04-11 04:17 UTC, raaCodeCat commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            "   sum(case when rr.islike then 1 else 0 end) - " +
Переделал архитектуру с булевого значения на оценку (+1 /-1).

2024-04-11 04:17 UTC, raaCodeCat commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            "coalesce(" +
Переделал архитектуру с булевого значения на оценку (+1 /-1).

2024-04-11 05:00 UTC, Cra5h23 commented on src/main/java/ru/yandex/practicum/filmorate/util/film/FilmUtil.java
> +    private static Set<Genre> makeGenreList(ResultSet rs) throws SQLException {
Убрал ненужную проверку

2024-04-11 05:00 UTC, Cra5h23 commented on src/main/java/ru/yandex/practicum/filmorate/util/film/FilmUtil.java
> +    private static List<Director> makeDirectorList(ResultSet rs) throws SQLException {
Убрал ненужную проверку

2024-04-11 05:01 UTC, Cra5h23 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoImpl.java
> +        var sql = "delete directors where director_id = ?;";
Убрал ненужную точку с запятой.

2024-04-11 05:02 UTC, Cra5h23 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +                if (params[1].equals("year")) {
Поменял местами

2024-04-11 06:30 UTC, raaCodeCat commented on src/main/java/ru/yandex/practicum/filmorate/service/film/impl/FilmServiceImpl.java
> +        List<Like> likes = likeDao.getAllFilmLikes();
Перенёс логику поиска рекомендаций по фильмам на строну БД.

2024-04-11 08:24 UTC, Cra5h23 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.warn("Ошибка работы с жанрами:" + e.fillInStackTrace());
Поправил логи.

2024-04-11 12:09 UTC, byLucz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +                    if (value > 1895) {
Потому что в тесте есть запрос {{baseUrl}}/films/popular?genreId=3, где params[1] является жанром. А в то, что когда-либо будет создано почти 2000 жанров или по неизвестным причинам люди вдруг перейдут на новый вид календаря, я верю гораздо меньше, чем в то, что потенциальные пользователи приложения перепутают местами query параметры.

2024-04-12 11:47 UTC, kvach2avl reviewed
ok

2024-04-12 11:47 UTC, kvach2avl commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDaoImpl.java
> +                "       SELECT DISTINCT user_id FROM likes AS fl_1\n" +
Лучше немного доработать этот запрос следующим образом:
1. добавить в него (а не во внешний запрос) условие на существование лайков, отсутствующих у целевого пользователя;
2. отсортировать пользователей по количеству совпадений по лайкам в порядке убывания;
3. выбрать из N-первых, где N-какое-то разумное число (10-20).

Тогда рекомендация будет репрезентативной - в неё в первую очередь попадут фильмы из "фильмографии" тех, с кем у данного пользователя больше совпадений по вкусам. И эта выборка всегда будет относительно небольшой. В нынешней же реализации всё ещё присутствуют шансы получить всю БД в выгрузке

2024-04-13 13:08 UTC, mikita95 requested changes
Все сделано отлично :) Отличная командная работа. Оставил лишь небольшие замечания

2024-04-13 13:08 UTC, mikita95 commented on src/main/resources/schema.sql
> +user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
Стоит также добавить индексы на колонки, по которым выполняются запросы, так будет эффективнее

2024-04-13 13:08 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/config/ClockConfig.java
> +public class ClockConfig {
Лучше было бы сделать просто сервис, который бы возвращал clock, так немного избыточно делать Бин для clock

2024-09-08 13:46 UTC, merged